version: '3.5'
services:
  redis:
    image: redis:5.0.3
    ports:
      - '127.0.0.1:6379:6379'
    expose:
      - '6379'
    volumes:
      - ./redis.conf:/redis.conf
      - ./data:/data
    command: ['redis-server', '/redis.conf']
